# Generated by Django 4.2.13 on 2026-05-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('alt_number', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('local_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('aadhar_pan', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
